/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElImage: typeof import('element-plus/es')['ElImage']
    Forgot_Password: typeof import('./src/components/operate/Forgot_Password.vue')['default']
    HomePage: typeof import('./src/components/operate/HomePage.vue')['default']
    Login: typeof import('./src/components/operate/Login.vue')['default']
    Login_Form: typeof import('./src/components/operate/Login_Form.vue')['default']
    Register_Form: typeof import('./src/components/operate/Register_Form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
